/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:86d87c5c-1797-4e58-b25b-d8e4295a9dc4",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_mdwK5Qybi",
    "aws_user_pools_web_client_id": "3rqjq2a79pkohapv6urh9qqpgb",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://v2kxbshss5bnlj2va3asrw6vwq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qnnwj5ishjdn5eukosg5253ae4",
    "aws_content_delivery_bucket": "amplifyapp-20210211012931-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "http://amplifyapp-20210211012931-hostingbucket-dev.s3-website-eu-west-1.amazonaws.com"
};


export default awsmobile;
